### PR TITLE
Add support for ready event

### PR DESCRIPTION
**Pull request by amiel**
This will allow me ito add a loading indicator to my application and easily hide it when the element is ready.

### CODE REVIEW

**Comment by amiel** [comment]
Check out #30 for a fix on CI. I'll be happy to rebase this back on master when/if #30 is merged.

**Comment by amiel** [comment]
Hi, sorry to bother, but I'd love to use this in my app and reference the official version of this addon.

Is this something you'd be willing to look in to merging?

Thanks for your time :)

**Comment by begedin** [comment]
Hey @amiel. 

Again, sorry for the delayed response. We see no reason not to include this change, however, the build seems to be failing, possibly due to lacking the fix from your other PR.

**Comment by amiel** [comment]
@begedin No worries and thanks for taking the time to respond and merge my other PR (#30).

I have rebased this one on master now that #30 has been merged and it looks like the test suite is green again.

I would super appreciate a release in the near future with this change if you get a chance. This way I can add a loading indicator to our new stripe elements :)

Thanks again 😄

**Comment by begedin** [comment]
Sorry for the delay, again. Not seeing a reason not to support this. So merging.

**Comment by amiel** [comment]
Awesome, thanks!

**Pull request merged**
