### PR TITLE
Fix component destroy error

### PR DESCRIPTION
**Pull request by StevenElberger**
Mirrors the work done in PR #40 (original author has not updated their branch yet).

### CODE REVIEW

**Comment by josemarluedke** [comment]
@joshsmith @snewcomer Any change to get this merged soon?

**Comment by lindyhopchris** [comment]
I can get this merged, but I'm not sure `sendAction` is right as it's deprecated. So think it needs to use `get(this, 'blur')(event)`

However the event on the Stripe element won't be firing within the Ember runloop, so we might need to also wrap this in a `once()` from `@ember/runloop`?

**Comment by josemarluedke** [comment]
Yeah, `sendAction` should be avoided. This should also check if the properties are functions.

Example: 
```js
    stripeElement.on('blur', (event) => {
      if (this.isDestroying || this.isDestroyed) {
        return;
      }
      if (typeof this.blur === 'function') {
        this.blur(stripeElement, event)
      }
    });
```

**Comment by lindyhopchris** [comment]
Don't we need to put this on the Ember runloop? Something like:

```js
stripeElement.on('blur', (event) => {
   once(this, '_invokeAction', 'blur', stripeElement, event);
});
```

then:

```js
_invokeAction(method, stripeElement, event) {
    if (this.isDestroying || this.isDestroyed) {
      return;
    }

    if (typeof this[method] === 'function') {
      this[method](stripeElement, event)
    }
}
```

**Comment by lindyhopchris** [comment]
Closed in favour of #62

**Pull request closed without merging**
